### PR TITLE
Fix issue with import object for custom scalar type

### LINKED ISSUE #179: Fallback to Object generation for variables not correctly supported by compiler causes wrong import
Prerequisites: no custom type mapping specified in gradle config.

Having next query:
```
query SimpleQuery($id:IdOrUrl!)
{
  article(id: $id) {
    url summary
  }
}
```

Generate model:
```
package com.example;
**import Object.Object;**
....

@Generated("Apollo GraphQL")
public final class SimpleQuery implements Query<SimpleQuery.Variables> {
  public static final String OPERATION_DEFINITION = "query SimpleQuery($id: IdOrUrl!) {\n"
      + "  article(id: $id) {\n"
      + "    __typename\n"
      + "    url\n"
      + "    summary\n"
      + "  }\n"
      + "}";

...

public static final class Variables extends Operation.Variables {
    private final @Nonnull Object id;
    Variables(@Nonnull Object id) {
      this.id = id;
    }
    public @Nonnull Object id() {
      return id;
    }

```

### PR DESCRIPTION
**Pull request by sav007**
Closes #179

### CODE REVIEW

File: apollo-compiler/src/main/kotlin/com/apollographql/android/compiler/Util.kt [hunk 1]
```diff
@@ -166,6 +166,9 @@ fun TypeSpec.withValueInitConstructor(): TypeSpec {
       .build()
 }
 
+fun String.toJavaType(): ClassName =
+    ClassName.get(substringBeforeLast(delimiter = ".", missingDelimiterValue = ""), substringAfterLast("."))
```
Comment (digitalbuddha) [inline apollo-compiler/src/main/kotlin/com/apollographql/android/compiler/Util.kt]: Pretty!
