### PR TITLE
Response body empty when HttpException throw

### LINKED ISSUE #361: Response body empty when HttpException thrown
Our GraphQL endpoint requires OAuth authentication. When we use the apollo client to hit our endpoint and our endpoint returns a status code of `401`, the apollo client throws an `HttpException` with a `okhttp3.Response` object. The problem is, before the exception is thrown, the `Response` is closed. This means when we try to read the body of the `Response` when we try to handle the exception, it is blank.  

This is from `ApolloParseInterceptor#parse` which is where the premature closure of the response happens:
```java
  Util.closeQuietly(response);
  throw new HttpException(response);
```

A solution to this could be to not to add a `Response` to the exception. We can instead create an immutable object, say `NetworkResponse` that has a `responseBody` and `responseCode` that we can add to the exception.

### PR DESCRIPTION
**Pull request by sav007**
Closes #361 

@mandrizzle

### CODE REVIEW

File: apollo-runtime/src/test/java/com/apollographql/android/impl/InterceptorTest.java [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+
+        @Override public Object wrapData(Data data) {
+          return data;
+        }
+      }).execute();
+      fail("Expected HttpException");
+    } catch (HttpException httpException) {
+      assertThat(httpException.code()).isEqualTo(401);
+      assertThat(httpException.message()).isEqualTo("Client Error");
+      assertThat(httpException.rawResponse().body().string()).isEqualTo("Unauthorized request!");
```
Comment (mandrizzle) [inline apollo-runtime/src/test/java/com/apollographql/android/impl/InterceptorTest.java]: Is is a good idea to not close the body of the response? I am not sure of the implications of not doing so. Personally, I would have changed the `HttpException` class to have a static method that looks like:

```java
  public static HttpException from(Response response) throws IOException {
     try {
       String body = response.body() != null ? response.body().string() : "";
       return new HttpException(response, response.code(), response.message(), body);
     } finally {
       closeQuietly(response);
     }
   }
```

So that the body does get closed but before it does, we have read the contents of it. Also IIRC, the `ResponseBody` in the `Response` object is what gets closed when `close` is called. So if we read and copy the contents over, it is probably safe to close.

File: apollo-runtime/src/main/java/com/apollographql/android/impl/util/HttpException.java [hunk 2]
```diff
@@ -1,15 +1,37 @@
...
 
+import javax.annotation.Nullable;
+
 import okhttp3.Response;
 
 public class HttpException extends RuntimeException {
-  private final okhttp3.Response rawResponse;
+  private final int code;
+  private final String message;
+  private final Response rawResponse;
```
Comment (mandrizzle) [inline apollo-runtime/src/main/java/com/apollographql/android/impl/util/HttpException.java]: Since `Response` isn't `Serializable`, this is a good time to add `transient` to this since technically `Exceptions` should be `Serializable`

File: apollo-runtime/src/test/java/com/apollographql/android/impl/InterceptorTest.java (hunk 1 above)
Comment (mandrizzle) [inline apollo-runtime/src/test/java/com/apollographql/android/impl/InterceptorTest.java]: Just to add, calling `string()` does close `ResponseBody` but if no one was to call it, it would not close.

**Comment by mandrizzle** [comment]
Just throwing out an idea here. What if we reserve `onFailure` for `IOExceptions`aka network issues but repurpose `graphql.Response` to also return server errors?

I mention this because as of right now, I think the public api for the `ApolloClient` is easy to screw up. 

1. `onFailure` passes in a `Throwable` which means one needs to be aware to cast what is passed in back to an `HttpException` to be able to read server errors. 

2.  After thinking about it, I think we shouldn't close the `ResponseBody` and instead, leave it for the consumer to close it. Because the consumer might want to read in the `ResponseBody` from the error via `BufferedSource` rather than as a `String`. Now the problem I see is, since the `ResponseBody` that we need to close is part of the `Exception` that is thrown, it can easily be ignored or lost which means people might see [this](https://github.com/square/okhttp/issues/2311)

3. There are other implications having non 200 status codes being returned as exceptions. One that I can think of is how a server error can kill a `rx` stream from the `RxApollo` package when really calling `onError` in streams should be for fatal, unrecoverable, exceptions. See [here](http://blog.danlew.net/2015/12/08/error-handling-in-rxjava/) for more details on that.

Thoughts on this? I realize it might require a bigger, breaking, change but may be worth it.

**Comment by sav007** [comment]
@mandrizzle Thanks, these are good points:

>What if we reserve onFailure for IOExceptionsaka network issues but repurpose graphql.Response to also return server errors

>1 onFailure passes in a Throwable which means one needs to be aware to cast what is passed in back to an HttpException to be able to read server errors.

Except IOException we can potentially have: `JsonDataException`, `JsonEncodingException`.
I suggest to not include any exceptions in `graphql.Response` as this object represents the real response from server (with errors returned by GraphQL). But I suggest to wrap all Exceptions into some thing like checked `ApolloException`. So `OnFailure` will always get the `ApolloException` with cause == original one

>2 After thinking about it, I think we shouldn't close the ResponseBody and instead, leave it for the consumer to close it. Because the consumer might want to read in the ResponseBody from the error via BufferedSource rather than as a String. Now the problem I see is, since the ResponseBody that we need to close is part of the Exception that is thrown, it can easily be ignored or lost which means people might see this

That the tradeoff of giving user to parse error body. And this is the contract that user must follow always close `ApolloException`

>3 There are other implications having non 200 status codes being returned as exceptions. One that I can think of is how a server error can kill a rx stream from the RxApollo package when really calling onError in streams should be for fatal, unrecoverable, exceptions. See here for more details on that.

That's issue of Rx wrapper if user don't want to break the rx chain he must wrap the error (for example with onErrorResumeNext or smth). So this is not part of ApolloClient itself as it's a pure java module, but we can think about this in context of our RxWrapper
