### PR TITLE
[KMP] set the Content-Type to `application/json; charset=utf-8` on iOS as well

### LINKED ISSUE #2665: Multiplatform - wrong content-type by default on iOS
**Summary**
The content-type header value on iOS by default is `application/x-www-form-urlencoded` instead of `application/json; charset=utf-8` on android. 

**Version**
2.4.1

**Description**

The content-type header value on iOS by default is `application/x-www-form-urlencoded` instead of `application/json; charset=utf-8` on android. 

This leads to server HTTP 400 Response.

If manually override header to `application/json` (like in example below) then request works on both platforms.

```
return ApolloClient(
            networkTransport = ApolloHttpNetworkTransport(
                serverUrl,
                mapOf("content-type" to "application/json; charset=utf-8") // Fix default content-type on iOS
            ),
            interceptors = listOf(bearerTokenInterceptor, loggingInterceptor, errorInterceptor),
            scalarTypeAdapters = ScalarTypeAdapters(getCustomTypeAdapters()),
        )
```

### PR DESCRIPTION
**Pull request by martinbonnin**
closes #2665

### CODE REVIEW

**Review by tasomaniac — APPROVED** [review]

File: apollo-runtime-kotlin/src/iosMain/kotlin/com/apollographql/apollo/network/http/ApolloHttpNetworkTransport.kt [hunk 1]
```diff
@@ -152,6 +152,7 @@ actual class ApolloHttpNetworkTransport(
       val postBody = operation.composeRequestBody(scalarTypeAdapters).toByteArray().toNSData()
       setHTTPMethod("POST")
       headers
+          .plus("Content-Type" to "application/json; charset=utf-8")
```
Comment (tasomaniac) [inline apollo-runtime-kotlin/src/iosMain/kotlin/com/apollographql/apollo/network/http/ApolloHttpNetworkTransport.kt:155]: Is this something we can test?

**Review by sav007 — APPROVED** [review]

File: apollo-runtime-kotlin/src/iosMain/kotlin/com/apollographql/apollo/network/http/ApolloHttpNetworkTransport.kt (hunk 1 above)
Comment (martinbonnin) [reply apollo-runtime-kotlin/src/iosMain/kotlin/com/apollographql/apollo/network/http/ApolloHttpNetworkTransport.kt:155]: I must admit I'm a bit lazy to add a test there. The only thing I can think of is to use a mock server and check the headers but that feels like a lot of code for something that most likely won't be changing too much?

Comment (tasomaniac) [reply apollo-runtime-kotlin/src/iosMain/kotlin/com/apollographql/apollo/network/http/ApolloHttpNetworkTransport.kt:155]: 👌
