### PR TITLE
[Runtime] convert RealResponseWriter.java to Kotlin

### LINKED ISSUE #2289: ApolloStore.write fragment crash on execute
**Summary**
Crash with log:
```
java.lang.AbstractMethodError: abstract method "void com.apollographql.apollo.api.internal.ResponseWriter.writeList(com.apollographql.apollo.api.ResponseField, java.util.List, kotlin.jvm.functions.Function2)"
        at com.*.core.apollo.fragment.FullArticleCard$Entities$marshaller$$inlined$invoke$1.marshal(ResponseFieldMarshaller.kt:19)
        at com.apollographql.apollo.internal.response.RealResponseWriter.writeObject(RealResponseWriter.java:64)
        at com.*.core.apollo.fragment.FullArticleCard$marshaller$$inlined$invoke$1.marshal(ResponseFieldMarshaller.kt:22)
        at com.apollographql.apollo.internal.RealApolloStore$21.execute(RealApolloStore.java:453)
```

While writing a `Fragment` to `ApolloStore` with 

```kotlin
  fun write(
      fragment: GraphqlFragment,
      cacheKey: CacheKey,
      variables: Operation.Variables
  ): ApolloStoreOperation<Set<String>>
```

**Description**
Full method call here:
```kotlin
private fun updateCache() {
        val cacheKey = "cache-key-here"
        val articleFragment = apolloClient.apolloStore.read(
            ResponseFieldMapper { FullArticleCard(it) },
            CacheKey.from(cacheKey),
            Operation.EMPTY_VARIABLES
        ).execute()

        val newNestedFragment = articleFragment.nestedFragmnt.copy(property = newProperty)
        val updatedArticleFragment = articleFragment.copy(nestedFragment = newNestedFragment)

        val saveCacheOperation = apolloClient.apolloStore.write(
            updatedArticleFragment,
            CacheKey.from(cacheKey),
            Operation.EMPTY_VARIABLES
        )

        saveCacheOperation.execute()
    }
```

Generated Fragment Code (Not a full code, only included relevant classes for now)

```kotlin
@Suppress("NAME_SHADOWING", "UNUSED_ANONYMOUS_PARAMETER", "LocalVariableName",
    "RemoveExplicitTypeArguments", "NestedLambdaShadowedImplicitParameter")
data class FullArticleCard(
  val __typename: String = "Article",
  val id: String,
  val entities: Entities,
) : GraphqlFragment {
  override fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller.invoke { writer ->
    writer.writeString(RESPONSE_FIELDS[0], this@FullArticleCard.__typename)
    writer.writeCustom(RESPONSE_FIELDS[1] as ResponseField.CustomTypeField, this@FullArticleCard.id)
    writer.writeObject(RESPONSE_FIELDS[4], this@FullArticleCard.entities.marshaller())
  }

  companion object {
    private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
        ResponseField.forString("__typename", "__typename", null, false, null),
        ResponseField.forCustomType("id", "id", null, false, CustomType.ID, null),
        ResponseField.forObject("entities", "entities", null, false, null)
        )

    val FRAGMENT_DEFINITION: String = """
        |fragment fullArticleCard on Article {
        |  __typename
        |  id
        |  entities {
        |    __typename
        |    nodes {
        |      __typename
        |      entityId
        |      label
        |    }
        |  }
        |}
        """.trimMargin()

    operator fun invoke(reader: ResponseReader): FullArticleCard = reader.run {
      val __typename = readString(RESPONSE_FIELDS[0])!!
      val id = readCustomType<String>(RESPONSE_FIELDS[1] as ResponseField.CustomTypeField)!!
      val entities = readObject<Entities>(RESPONSE_FIELDS[4]) { reader ->
        Entities(reader)
      }!!
      FullArticleCard(
        __typename = __typename,
        id = id,
        entities = entities
      )
    }

    @Suppress("FunctionName")
    fun Mapper(): ResponseFieldMapper<FullArticleCard> = ResponseFieldMapper { invoke(it) }
  }

  data class Node(
    val __typename: String = "Entity",
    /**
     * A unique identifier in the form Qxxx or Bxxx
     */
    val entityId: String,
    /**
     * Describes the entity in the requested language
     */
    val label: String
  ) {
    fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller.invoke { writer ->
      writer.writeString(RESPONSE_FIELDS[0], this@Node.__typename)
      writer.writeString(RESPONSE_FIELDS[1], this@Node.entityId)
      writer.writeString(RESPONSE_FIELDS[2], this@Node.label)
    }

    companion object {
      private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
          ResponseField.forString("__typename", "__typename", null, false, null),
          ResponseField.forString("entityId", "entityId", null, false, null),
          ResponseField.forString("label", "label", null, false, null)
          )

      operator fun invoke(reader: ResponseReader): Node = reader.run {
        val __typename = readString(RESPONSE_FIELDS[0])!!
        val entityId = readString(RESPONSE_FIELDS[1])!!
        val label = readString(RESPONSE_FIELDS[2])!!
        Node(
          __typename = __typename,
          entityId = entityId,
          label = label
        )
      }

      @Suppress("FunctionName")
      fun Mapper(): ResponseFieldMapper<Node> = ResponseFieldMapper { invoke(it) }
    }
  }

  /**
   * The connection type for Entity.
   */
  data class Entities(
    val __typename: String = "EntityConnection",
    /**
     * A list of nodes.
     */
    val nodes: List<Node?>?
  ) {
    fun marshaller(): ResponseFieldMarshaller = ResponseFieldMarshaller.invoke { writer ->
      writer.writeString(RESPONSE_FIELDS[0], this@Entities.__typename)
      writer.writeList(RESPONSE_FIELDS[1], this@Entities.nodes) { value, listItemWriter ->
        value?.forEach { value ->
          listItemWriter.writeObject(value?.marshaller())}
      }
    }

    companion object {
      private val RESPONSE_FIELDS: Array<ResponseField> = arrayOf(
          ResponseField.forString("__typename", "__typename", null, false, null),
          ResponseField.forList("nodes", "nodes", null, true, null)
          )

      operator fun invoke(reader: ResponseReader): Entities = reader.run {
        val __typename = readString(RESPONSE_FIELDS[0])!!
        val nodes = readList<Node>(RESPONSE_FIELDS[1]) { reader ->
          reader.readObject<Node> { reader ->
            Node(reader)
          }
        }
        Entities(
          __typename = __typename,
          nodes = nodes
        )
      }

      @Suppress("FunctionName")
      fun Mapper(): ResponseFieldMapper<Entities> = ResponseFieldMapper { invoke(it) }
    }
  }
}
```

Actual crash happens when Entities marshaller tries to writeList

```kotlin
writer.writeList(RESPONSE_FIELDS[1], this@Entities.nodes) { value, listItemWriter ->
        value?.forEach { value ->
          listItemWriter.writeObject(value?.marshaller())}
      }
```

**Version**
2.0.3

### PR DESCRIPTION
**Pull request by martinbonnin**
closes #2289 

Kotlin does not generate Java8 default methods by default but instead delegates to a `DefaultImpls` static class. This should certainly have caused a compile time issue but since the method was annotated with `@JvmSynthetic`, I guess the java compiler didn't check it. 
Converting RealResponseWriter.java to kotlin will make sure the `writeList` method is callable.

### CODE REVIEW

File: apollo-runtime/src/main/java/com/apollographql/apollo/internal/response/RealResponseWriter.kt [hunk 1]
```diff
@@ -0,0 +1,224 @@
...
+  }
+
+  private fun writeScalarFieldValue(field: ResponseField, value: Any?) {
+    checkFieldValue(field, value)
+    buffer[field.responseName] = FieldDescriptor(field, value)
+  }
+
+  private fun rawFieldValues(buffer: Map<String, FieldDescriptor>?): Map<String, Any?> {
+    val fieldValues: MutableMap<String, Any?> = LinkedHashMap()
+    for ((fieldResponseName, value) in buffer!!) {
```
Comment (tasomaniac) [inline apollo-runtime/src/main/java/com/apollographql/apollo/internal/response/RealResponseWriter.kt:79]: If this is the case, buffer above shouldn't be nullable

File: apollo-runtime/src/main/java/com/apollographql/apollo/internal/response/RealResponseWriter.kt [hunk 2]
```diff
@@ -0,0 +1,224 @@
...
+        listValues.add(rawListFieldValues(value))
+      } else {
+        listValues.add(value)
+      }
+    }
+    return listValues
+  }
+
+  private fun resolveFields(operationVariables: Operation.Variables,
+                            delegate: ResolveDelegate<Map<String, Any>?>, buffer: Map<String, FieldDescriptor>?) {
```
Comment (tasomaniac) [inline apollo-runtime/src/main/java/com/apollographql/apollo/internal/response/RealResponseWriter.kt:110]: Same here

File: apollo-runtime/src/main/java/com/apollographql/apollo/internal/response/RealResponseWriter.kt [hunk 3]
```diff
@@ -0,0 +1,224 @@
...
+          } else {
+            delegate.didResolveScalar(rawFieldValue)
+          }
+        }
+      }
+      delegate.didResolve(fieldDescriptor.field, operationVariables)
+    }
+  }
+
+  private fun resolveObjectFields(fieldDescriptor: FieldDescriptor?,
```
Comment (tasomaniac) [inline apollo-runtime/src/main/java/com/apollographql/apollo/internal/response/RealResponseWriter.kt:135]: Same here

File: apollo-runtime/src/main/java/com/apollographql/apollo/internal/response/RealResponseWriter.kt (hunk 1 above)
Comment (martinbonnin) [reply apollo-runtime/src/main/java/com/apollographql/apollo/internal/response/RealResponseWriter.kt]: I could remove this `!!` and a few other ones. There are still a few in the file that I'm not sure we can remove easily/safely.

File: apollo-runtime/src/main/java/com/apollographql/apollo/internal/response/RealResponseWriter.kt [hunk 4]
```diff
@@ -0,0 +1,225 @@
...
+    delegate.didResolveObject(fieldDescriptor.field, rawFieldValues)
+  }
+
+  private fun resolveListField(listResponseField: ResponseField, fieldValues: List<*>?,
+                               rawFieldValues: List<*>?, delegate: ResolveDelegate<Map<String, Any>?>) {
+    if (fieldValues == null) {
+      delegate.didResolveNull()
+      return
+    }
+    for (i in fieldValues.indices) {
```
Comment (tasomaniac) [inline apollo-runtime/src/main/java/com/apollographql/apollo/internal/response/RealResponseWriter.kt:153]: This can be replaced with forEachWithIndex. Could be little bit better but this is also good.
