### PR TITLE
Fix generation of nested structures with the same name results in compiler errors

### LINKED ISSUE #169: Generation of nested structures with the same name results in compiler errors
There appears to be an issue with nested structures which define the same name multiple times. 

Briefly, a structure such as:
```
mutation UpvotePost($postId: Int!) {
  upvotePost(postId: $postId) {
    ...PostDetails
  }
}
```

results in a generated class like:
```
public final class UpvotePost implements Mutation<UpvotePost.Variables> {
    public static class Data implements Operation.Data {
        public static class UpvotePost { ... }
    }
}
```

which has a compilation error.

### PR DESCRIPTION
**Pull request by sav007**
Closes #169

### CODE REVIEW

File: apollo-compiler/src/test/graphql/com/example/unique_type_name/HeroDetailQueryExpected.java [hunk 1]
```diff
@@ -61,9 +61,9 @@ public String queryDocument() {
   }
 
   public interface Data extends Operation.Data {
-    @Nullable Hero hero();
+    @Nullable HeroDetailQuery$ heroDetailQuery();
```
Comment (digitalbuddha) [inline apollo-compiler/src/test/graphql/com/example/unique_type_name/HeroDetailQueryExpected.java]: what happens if nested twice?  tbh I'd prefer `HeroDetailQuery$$1`

Comment (sav007) [inline apollo-compiler/src/test/graphql/com/example/unique_type_name/HeroDetailQueryExpected.java]: It will be `HeroDetailQuery$$`

Comment (digitalbuddha) [inline apollo-compiler/src/test/graphql/com/example/unique_type_name/HeroDetailQueryExpected.java]: And just for clarity 5 would be Query$$$$$ so just as example imagine you see following in logs... 
NullPointerExxeption: Foo$$$$ is null 

Will you be able to tell without dragging your finger in screen whether that was 4 or 5 dollar signs. 
I don't feel strongly about it but can see it leading to confusing traces. As example rxjava does Action0  -  Action9

Comment (sav007) [inline apollo-compiler/src/test/graphql/com/example/unique_type_name/HeroDetailQueryExpected.java]: Not sure why we initially decided to go with $, but it's really easy to change in compiler. But the idea that you in most cases you won't have such issue with more than 2-3 nested classes with the same name. But I don't have any strong opinion for this as Hero4 and Hero$$$$ from my perspective is the same evil, and for sure I will try to avoid such queries with the same nested names (will use aliases)

Comment (sav007) [inline apollo-compiler/src/test/graphql/com/example/unique_type_name/HeroDetailQueryExpected.java]: @digitalbuddha so are we changing $ to number or leaving as is?

Comment (digitalbuddha) [inline apollo-compiler/src/test/graphql/com/example/unique_type_name/HeroDetailQueryExpected.java]: I prefer number but you make the call :-)

**Comment by digitalbuddha** [comment]
Now you can blame me if people don't like it ☺️

**Comment by digitalbuddha** [comment]
```
com.apollographql.android.compiler.CodeGenTest >  generateExpectedClasses[pojo_fragment_with_inline_fragment] FAILED
    org.junit.ComparisonFailure at CodegenTest.kt:31
```
