### PR TITLE
[SDL] add support for type extensions

### LINKED ISSUE #2656: Support for type extensions in schema
Hey there 👋 

In a project I'm working on, we are using type extension, like this:

```
type A {
    field
}

extend type A {
    newField
}
```

Right now, it doesn't work as the codegen doesn't detect any field added in the extension. Do you think it would be possible to handle this?

Many thanks!

### PR DESCRIPTION
**Pull request by martinbonnin**
Add support for SDL type extensions: https://spec.graphql.org/June2018/#sec-Type-System-Extensions

closes #2656

PS: This PR also adds a test case for operation directives, (see #2661)

### CODE REVIEW

File: apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/parser/sdl/GraphSDLSchemaParser.kt [hunk 1]
```diff
@@ -106,6 +109,218 @@ object GraphSDLSchemaParser {
...
+
+  private fun GraphSDLParser.ScalarTypeExtensionDefinitionContext.parse(typeDefinitions: MutableMap<String, GraphSdlSchema.TypeDefinition>) {
+    val name = name().text
+    val scalar = typeDefinitions.get(name)
+    if (scalar == null) {
+      throw ParseException(
+          message = "Cannot add scalar type extension on unknown scalar `$name`",
+          token = start
+      )
+    }
```
Comment (sav007) [inline apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/parser/sdl/GraphSDLSchemaParser.kt:135]: nit:  just a preference
```
val scalar = typeDefinitions.get(name) ?: throw ParseException(
          message = "Cannot add scalar type extension on unknown scalar `$name`",
          token = start
      )
```

File: apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/parser/sdl/GraphSDLSchemaParser.kt [hunk 2]
```diff
@@ -106,6 +109,218 @@ object GraphSDLSchemaParser {
     )
   }
 
+  private fun List<GraphSDLParser.TypeSystemExtensionContext>.parse(
+      typeDefinitions: MutableMap<String, GraphSdlSchema.TypeDefinition>
```
Comment (sav007) [inline apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/parser/sdl/GraphSDLSchemaParser.kt:113]: not a big fan of passing mutable map and having side affect to mutate `typeDefinitions` map, but don't see easy way to make it pure. We might consider to rename this function to smth that describes mutation maybe like `MutableMap<String, GraphSdlSchema.TypeDefinition>.decorateWithTypeExtentantion()`?

File: apollo-compiler/src/test/graphql/com/example/operation_directive/TestOperation.graphql [hunk 3]
```diff
@@ -0,0 +1,5 @@
+query TestQuery @myModifier {
```
Comment (sav007) [inline apollo-compiler/src/test/graphql/com/example/operation_directive/TestOperation.graphql:1]: that interesting am I right that this `myModifier` directive is not declared in the schema? I thought that GraphQL spec says that directive also must be declared in the schema?

Comment (martinbonnin) [reply apollo-compiler/src/test/graphql/com/example/operation_directive/TestOperation.graphql:1]: Yup, that's 100% correct. I added this test as part of checking https://github.com/apollographql/apollo-android/issues/2661. 

But since `myModifier` is not in the schema, this means we're missing some validation there. I added https://github.com/apollographql/apollo-android/issues/2673 as a follow up.

File: apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/parser/sdl/GraphSDLSchemaParser.kt (hunk 1 above)
Comment (martinbonnin) [reply apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/parser/sdl/GraphSDLSchemaParser.kt]: IntelliJ agrees with you and put yellow underlines. I replaced with them.

File: apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/parser/sdl/GraphSDLSchemaParser.kt (hunk 2 above)
Comment (martinbonnin) [reply apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/parser/sdl/GraphSDLSchemaParser.kt]: Yea, not a huge fan for mutable maps either. I just pushed a new version with a `fold`. That's a lot more copying Maps all over the place but I think that's the price to pay for immutability.

File: apollo-compiler/src/test/graphql/com/example/operation_directive/TestOperation.graphql (hunk 3 above)
Comment (sav007) [reply apollo-compiler/src/test/graphql/com/example/operation_directive/TestOperation.graphql:1]: Yeah, I guess we missed that validation as we have tests for skip / include and I don't see them either in schema sdl.

**Review by sav007 — APPROVED** [review]
